# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      day: "friday"
      time: "7:02"
      timezone: "Europe/Warsaw"
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      day: "friday"
      time: "8:01"
      timezone: "Europe/Warsaw"
      interval: "weekly"
