name: "Check formatting"
description: "Checks code formatting by using cargo fmt"

runs:
  using: "composite"
  steps:
    - name: cargo fmt
      shell: bash -eoux pipefail {0}
      run: cargo fmt --all -- --check
