name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  style:
    timeout-minutes: 15
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.7
        with:
          clean: false
          fetch-depth: 0

      - name: Filter for Rust file changes only
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
            - 'src/*.rs'
      - if: steps.changes.outputs.files == 'src/*.rs'
          - name: Remove untracked files
            run: git clean -df

          - name: Run code style check
            uses: ./.github/actions/check_style
